version: '3'

services:
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server
    ports:
      - '6379:6379'

  flask:
    build: .
    restart: always
    env_file:
      - pypistats/secret/prod.env
    command: 'flask run --host=0.0.0.0'
    ports:
      - '5000:5000'

  celery:
    build: .
    restart: always
    env_file:
      - pypistats/secret/prod.env
    command: 'celery -A pypistats.run.celery worker -l info'
    user: nobody
    depends_on:
      - redis

  beat:
    build: .
    restart: always
    env_file:
      - pypistats/secret/prod.env
    command: 'celery beat -A pypistats.run.celery -l info --pidfile='
    depends_on:
      - redis
